// Common shared components — barrel export
export { default as PageHeader }     from './PageHeader'
export { default as Breadcrumb }     from './Breadcrumb'
export { default as DataTable }      from './DataTable'
export type { Column }               from './DataTable'
export { default as FormDrawer }     from './FormDrawer'
export { default as StatusBadge }    from './StatusBadge'
export { default as SearchFilter }   from './SearchFilter'
export { default as EmptyState }     from './EmptyState'
export { default as LoadingSpinner } from './LoadingSpinner'
export { default as EnterpriseSelect } from './EnterpriseSelect'
export type { EnterpriseSelectOption, EnterpriseSelectProps } from './EnterpriseSelect'
export { default as ToggleSwitch }     from './ToggleSwitch'
export type { ToggleSwitchProps }       from './ToggleSwitch'
export { default as DeleteConfirmDialog } from './DeleteConfirmDialog'
export { default as ConfirmModal } from './ConfirmModal'
export type { ConfirmVariant, ConfirmModalProps } from './ConfirmModal'
export { default as TableActionMenu } from '../shared/TableActionMenu'
export type { TableActionItem } from '../shared/TableActionMenu'

