import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

class AppLocalization {
  final Locale locale;
  AppLocalization(this.locale);

  static final Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'app_title': 'Enterprise POS',
      'login': 'Login',
      'username': 'Username',
      'enter_username': 'Enter username',
      'email': 'Email Address',
      'password': 'Password',
      'remember_me': 'Remember Me',
      'remember_device': 'Remember Device',
      'forgot_password': 'Forgot Password?',
      'welcome_back': 'Welcome Back',
      'login_subtitle': 'Enterprise Mobile ERP & POS Terminal',
      'sign_in_to_terminal': 'SIGN IN TO TERMINAL',
      'biometric_login': 'Biometric Login',
      'qr_login': 'Scan QR Login',
      'guest_demo': 'Guest Demo',
      'username_required': 'Username is required',
      'password_required': 'Password is required',
      'password_too_short': 'Password must be at least 6 characters',
      'forgot_password_sheet_title': 'Reset Account Password',
      'phone_or_username': 'Username or Phone Number',
      'send_otp': 'SEND VERIFICATION OTP',
      'enter_otp': 'Enter 6-Digit OTP',
      'new_password': 'New Password',
      'reset_success': 'Password reset successfully!',
      'home': 'Home',
      'pos': 'POS Terminal',
      'products': 'Products',
      'inventory': 'Inventory',
      'purchases': 'Purchases',
      'sales': 'Sales',
      'reports': 'Reports',
      'finance': 'Finance',
      'crm': 'CRM & Customers',
      'employees': 'Employees',
      'settings': 'Settings',
      'profile': 'Profile',
      'notifications': 'Notifications',
      'logout': 'Logout',
      'todays_sales': 'Today\'s Sales',
      'todays_purchase': 'Today\'s Purchase',
      'revenue': 'Revenue',
      'net_profit': 'Net Profit',
      'recent_orders': 'Recent Orders',
      'low_stock': 'Low Stock Alert',
      'checkout': 'Checkout',
      'cash': 'Cash',
      'khqr': 'KHQR Bakong',
      'card': 'Credit Card',
      'pay_now': 'Pay Now',
      'print_receipt': 'Print Receipt',
      'scan_qr': 'Scan QR Code',
      'offline_mode': 'Offline Mode (Auto Sync)',
    },
    'km': {
      'app_title': 'ប្រព័ន្ធលក់សហគ្រាស',
      'login': 'ចូលប្រព័ន្ធ',
      'username': 'ឈ្មោះអ្នកប្រើប្រាស់',
      'enter_username': 'បញ្ចូលឈ្មោះអ្នកប្រើប្រាស់',
      'email': 'អ៊ីមែល',
      'password': 'ពាក្យសម្ងាត់',
      'remember_me': 'ចងចាំខ្ញុំ',
      'remember_device': 'ចងចាំឧបករណ៍នេះ',
      'forgot_password': 'ភ្លេចពាក្យសម្ងាត់?',
      'welcome_back': 'ស្វាគមន៍ការត្រឡប់មកវិញ',
      'login_subtitle': 'ប្រព័ន្ធគ្រប់គ្រងសហគ្រាស និង POS',
      'sign_in_to_terminal': 'ចូលទៅកាន់ប្រព័ន្ធ',
      'biometric_login': 'ស្កែនក្រយ៉ៅដៃ / ទម្រង់មុខ',
      'qr_login': 'ស្កែន QR ចូលប្រព័ន្ធ',
      'guest_demo': 'គណនីសាកល្បង',
      'username_required': 'សូមបញ្ចូលឈ្មោះអ្នកប្រើប្រាស់',
      'password_required': 'សូមបញ្ចូលពាក្យសម្ងាត់',
      'password_too_short': 'ពាក្យសម្ងាត់យ៉ាងហោចណាស់ ៦ តួ',
      'forgot_password_sheet_title': 'កំណត់ពាក្យសម្ងាត់ឡើងវិញ',
      'phone_or_username': 'ឈ្មោះអ្នកប្រើប្រាស់ ឬលេខទូរស័ព្ទ',
      'send_otp': 'ផ្ញើសូដលេខ OTP',
      'enter_otp': 'បញ្ចូលកូដ OTP ៦ ខ្ទង់',
      'new_password': 'ពាក្យសម្ងាត់ថ្មី',
      'reset_success': 'កំណត់ពាក្យសម្ងាត់ជោគជ័យ!',
      'home': 'ទំព័រដើម',
      'pos': 'កន្លែងលក់ (POS)',
      'products': 'ទំនិញ',
      'inventory': 'ស្តុក',
      'purchases': 'ការទិញចូល',
      'sales': 'ការលក់',
      'reports': 'របាយការណ៍',
      'finance': 'ហិរញ្ញវត្ថុ',
      'crm': 'អតិថិជន',
      'employees': 'បុគ្គលិក',
      'settings': 'ការកំណត់',
      'profile': 'គណនី',
      'notifications': 'ការជូនដំណឹង',
      'logout': 'ចាកចេញ',
      'todays_sales': 'ការលក់ថ្ងៃនេះ',
      'todays_purchase': 'ការទិញថ្ងៃនេះ',
      'revenue': 'ចំណូលសរុប',
      'net_profit': 'ប្រាក់ចំណេញសុទ្ធ',
      'recent_orders': 'ការបញ្ជាទិញថ្មីៗ',
      'low_stock': 'ទំនិញជិតអស់ពីស្តុក',
      'checkout': 'គិតប្រាក់',
      'cash': 'ប្រាក់សុទ្ធ',
      'khqr': 'KHQR បាគង',
      'card': 'កាតធនាគារ',
      'pay_now': 'បង់ប្រាក់ឥឡូវនេះ',
      'print_receipt': 'បោះពុម្ពវិក្កយបត្រ',
      'scan_qr': 'ស្កែន QR',
      'offline_mode': 'របៀបអូហ្វឡាញ (សមកាលកម្មស្វ័យប្រវត្តិ)',
    },
    'th': {
      'app_title': 'ระบบขายหน้าร้านองค์กร',
      'login': 'เข้าสู่ระบบ',
      'username': 'ชื่อผู้ใช้',
      'enter_username': 'กรอกชื่อผู้ใช้',
      'email': 'อีเมล',
      'password': 'รหัสผ่าน',
      'remember_me': 'จดจำฉัน',
      'remember_device': 'จำอุปกรณ์นี้',
      'forgot_password': 'ลืมรหัสผ่าน?',
      'welcome_back': 'ยินดีต้อนรับกลับ',
      'login_subtitle': 'ระบบจัดการองค์กรและ POS',
      'sign_in_to_terminal': 'เข้าสู่ระบบเทอร์มินัล',
      'biometric_login': 'สแกนชีวมิติ',
      'qr_login': 'สแกน QR เข้าสู่ระบบ',
      'guest_demo': 'ทดลองใช้งาน',
      'username_required': 'กรุณากรอกชื่อผู้ใช้',
      'password_required': 'กรุณากรอกรหัสผ่าน',
      'password_too_short': 'รหัสผ่านต้องมีอย่างน้อย 6 ตัวอักษร',
      'forgot_password_sheet_title': 'ตั้งรหัสผ่านใหม่',
      'phone_or_username': 'ชื่อผู้ใช้หรือเบอร์โทรศัพท์',
      'send_otp': 'ส่งรหัส OTP',
      'enter_otp': 'กรอกรหัส OTP 6 หลัก',
      'new_password': 'รหัสผ่านใหม่',
      'reset_success': 'ตั้งรหัสผ่านใหม่เรียบร้อยแล้ว!',
      'home': 'หน้าแรก',
      'pos': 'ระบบขาย POS',
      'products': 'สินค้า',
      'inventory': 'คลังสินค้า',
      'purchases': 'การสั่งซื้อ',
      'sales': 'ยอดขาย',
      'reports': 'รายงาน',
      'finance': 'การเงิน',
      'crm': 'ลูกค้า',
      'employees': 'พนักงาน',
      'settings': 'ตั้งค่า',
      'profile': 'โปรไฟล์',
      'notifications': 'การแจ้งเตือน',
      'logout': 'ออกจากระบบ',
      'todays_sales': 'ยอดขายวันนี้',
      'todays_purchase': 'ยอดซื้อวันนี้',
      'revenue': 'รายได้รวม',
      'net_profit': 'กำไรสุทธิ',
      'recent_orders': 'รายการล่าสุด',
      'low_stock': 'สินค้าใกล้หมด',
      'checkout': 'ชำระเงิน',
      'cash': 'เงินสด',
      'khqr': 'KHQR สแกน',
      'card': 'บัตรเครดิต',
      'pay_now': 'ชำระเงินทันที',
      'print_receipt': 'พิมพ์ใบเสร็จ',
      'scan_qr': 'สแกน QR',
      'offline_mode': 'โหมดออฟไลน์',
    },
    'vi': {
      'app_title': 'Hệ Thống Bán Hàng Doanh Nghiệp',
      'login': 'Đăng Nhập',
      'username': 'Tên Đăng Nhập',
      'enter_username': 'Nhập tên đăng nhập',
      'email': 'Email',
      'password': 'Mật Khẩu',
      'remember_me': 'Ghi Nhớ',
      'remember_device': 'Ghi Nhớ Thiết Bị',
      'forgot_password': 'Quên Mật Khẩu?',
      'welcome_back': 'Chào Mừng Trở Lại',
      'login_subtitle': 'Hệ Thống Quản Trị ERP & POS Mobile',
      'sign_in_to_terminal': 'ĐĂNG NHẬP VÀO THIẾT BỊ',
      'biometric_login': 'Đăng Nhập Sinh Trắc Học',
      'qr_login': 'Quét Mã QR Đăng Nhập',
      'guest_demo': 'Dùng Thử Demo',
      'username_required': 'Vui lòng nhập tên đăng nhập',
      'password_required': 'Vui lòng nhập mật khẩu',
      'password_too_short': 'Mật khẩu phải có ít nhất 6 ký tự',
      'forgot_password_sheet_title': 'Đặt Lại Mật Khẩu',
      'phone_or_username': 'Tên đăng nhập hoặc Số điện thoại',
      'send_otp': 'GỬI MÃ OTP XÁC NHẬN',
      'enter_otp': 'Nhập Mã OTP 6 Chữ Số',
      'new_password': 'Mật Khẩu Mới',
      'reset_success': 'Đặt lại mật khẩu thành công!',
      'home': 'Trang Chủ',
      'pos': 'Điểm Bán Hàng',
      'products': 'Sản Phẩm',
      'inventory': 'Kho Hàng',
      'purchases': 'Nhập Hàng',
      'sales': 'Bán Hàng',
      'reports': 'Báo Cáo',
      'finance': 'Tài Chính',
      'crm': 'Khách Hàng',
      'employees': 'Nhân Viên',
      'settings': 'Cài Đặt',
      'profile': 'Hồ Sơ',
      'notifications': 'Thông Báo',
      'logout': 'Đăng Xuất',
      'todays_sales': 'Doanh Số Hôm Nay',
      'todays_purchase': 'Nhập Hàng Hôm Nay',
      'revenue': 'Doanh Thu',
      'net_profit': 'Lợi Nhuận Ròng',
      'recent_orders': 'Đơn Hàng Gần Đây',
      'low_stock': 'Cảnh Báo Tồn Kho',
      'checkout': 'Thanh Toán',
      'cash': 'Tiền Mặt',
      'khqr': 'KHQR Quét',
      'card': 'Thẻ Tín Dụng',
      'pay_now': 'Thanh Toán Ngay',
      'print_receipt': 'In Hóa Đơn',
      'scan_qr': 'Quét Mã QR',
      'offline_mode': 'Chế Độ Ngoại Tuyến',
    },
    'zh': {
      'app_title': '企业级 POS 系统',
      'login': '登录',
      'username': '用户名',
      'enter_username': '请输入用户名',
      'email': '电子邮箱',
      'password': '密码',
      'remember_me': '记住我',
      'remember_device': '记住此设备',
      'forgot_password': '忘记密码？',
      'welcome_back': '欢迎回来',
      'login_subtitle': '企业级 ERP 与 POS 收银终端',
      'sign_in_to_terminal': '登录终端',
      'biometric_login': '生物识别登录',
      'qr_login': '扫码登录',
      'guest_demo': '演示账号',
      'username_required': '请输入用户名',
      'password_required': '请输入密码',
      'password_too_short': '密码长度不能少于 6 位',
      'forgot_password_sheet_title': '重置账号密码',
      'phone_or_username': '用户名或手机号码',
      'send_otp': '发送验证码 OTP',
      'enter_otp': '输入 6 位数验证码',
      'new_password': '新密码',
      'reset_success': '密码重置成功！',
      'home': '首页',
      'pos': '收银终端',
      'products': '商品管理',
      'inventory': '库存管理',
      'purchases': '采购管理',
      'sales': '销售管理',
      'reports': '报表分析',
      'finance': '财务管理',
      'crm': '客户管理',
      'employees': '员工管理',
      'settings': '系统设置',
      'profile': '个人中心',
      'notifications': '消息通知',
      'logout': '退出登录',
      'todays_sales': '今日销售额',
      'todays_purchase': '今日采购额',
      'revenue': '总营业额',
      'net_profit': '净利润',
      'recent_orders': '最新订单',
      'low_stock': '库存预警',
      'checkout': '结账',
      'cash': '现金',
      'khqr': 'KHQR 扫码',
      'card': '信用卡',
      'pay_now': '立即支付',
      'print_receipt': '打印小票',
      'scan_qr': '扫二维码',
      'offline_mode': '离线模式 (自动同步)',
    },
  };

  String translate(String key) {
    final langCode = locale.languageCode;
    return _localizedValues[langCode]?[key] ?? _localizedValues['en']?[key] ?? key;
  }
}

final localeProvider = StateProvider<Locale>((ref) => const Locale('en'));

extension LocalizationHelper on BuildContext {
  String tr(WidgetRef ref, String key) {
    final loc = ref.watch(localeProvider);
    return AppLocalization(loc).translate(key);
  }
}
