import React from 'react'
import {
  TrendingUp,
  ShoppingCart,
  Users,
  Package,
  BarChart3,
  PieChart,
  ShoppingBag,
  AlertTriangle,
  DollarSign,
  Activity,
  Zap,
  Clock,
  Bell,
  Megaphone,
  Smile,
  Globe2,
  Smartphone,
  UserCheck,
} from 'lucide-react'

export type SupportedLang = 'km' | 'en' | 'zh' | 'th' | 'vi'

export interface MultiLangString {
  km: string
  en: string
  zh: string
  th: string
  vi: string
}

export interface WidgetDefinition {
  id: string
  name: MultiLangString
  description: MultiLangString
  category: 'kpi' | 'analytics' | 'inventory' | 'finance' | 'system'
  categoryLabel: MultiLangString
  icon: React.ComponentType<{ className?: string }>
  gradient: string
  badgeColor: string
  defaultSize: 'small' | 'medium' | 'large'
  defaultOrder: number
}

export const DASHBOARD_WIDGET_REGISTRY: Record<string, WidgetDefinition> = {
  business_alerts: {
    id: 'business_alerts',
    name: {
      km: 'ដំណឹង និងការជូនដំណឹងអាជីវកម្ម',
      en: 'Business Alerts & Feeds',
      zh: '商业警报与通知',
      th: 'การแจ้งเตือนธุรกิจ',
      vi: 'Cảnh báo & Thông báo doanh nghiệp',
    },
    description: {
      km: 'បង្ហាញការជូនដំណឹងសំខាន់ៗ ដំណឹងស្តុក និងសកម្មភាពមិនប្រក្រតី',
      en: 'Displays high-priority business alerts, low stock warnings, and unusual transactions',
      zh: '显示高优先级商业警报、低库存警告和异常交易',
      th: 'แสดงการแจ้งเตือนธุรกิจที่มีความสำคัญสูง คำเตือนสต็อกต่ำ และรายการผิดปกติ',
      vi: 'Hiển thị cảnh báo doanh nghiệp ưu tiên cao, cảnh báo kho thấp và giao dịch bất thường',
    },
    category: 'system',
    categoryLabel: {
      km: 'ប្រព័ន្ធ & ការជូនដំណឹង',
      en: 'System & Alerts',
      zh: '系统与警报',
      th: 'ระบบและการแจ้งเตือน',
      vi: 'Hệ thống & Cảnh báo',
    },
    icon: Bell,
    gradient: 'from-amber-500 to-rose-500',
    badgeColor: 'bg-amber-500/10 text-amber-600 dark:text-amber-400 border-amber-500/20',
    defaultSize: 'large',
    defaultOrder: 0,
  },
  today_sales: {
    id: 'today_sales',
    name: {
      km: 'ការលក់ប្រចាំថ្ងៃ (Today Sales)',
      en: 'Today Sales Revenue',
      zh: '今日销售额',
      th: 'ยอดขายวันนี้',
      vi: 'Doanh số bán hàng hôm nay',
    },
    description: {
      km: 'បង្ហាញចំណូលសរុបបានមកពីការលក់ប្រចាំថ្ងៃ',
      en: 'Displays today total sales revenue and trend',
      zh: '显示今日销售总收入及趋势',
      th: 'แสดงรายได้รวมจากการขายและแนวโน้มในวันนี้',
      vi: 'Hiển thị tổng doanh thu bán hàng và xu hướng hôm nay',
    },
    category: 'kpi',
    categoryLabel: {
      km: 'ពាណិជ្ជកម្ម & KPI',
      en: 'Commerce & KPI',
      zh: '商业与KPI',
      th: 'การค้า & KPI',
      vi: 'Thương mại & KPI',
    },
    icon: TrendingUp,
    gradient: 'from-blue-500 to-indigo-600',
    badgeColor: 'bg-blue-500/10 text-blue-600 dark:text-blue-400 border-blue-500/20',
    defaultSize: 'medium',
    defaultOrder: 1,
  },
  today_orders: {
    id: 'today_orders',
    name: {
      km: 'ការកុម្ម៉ង់ប្រចាំថ្ងៃ (Today Orders)',
      en: 'Today Orders Count',
      zh: '今日订单数',
      th: 'จำนวนคำสั่งซื้อวันนี้',
      vi: 'Số lượng đơn hàng hôm nay',
    },
    description: {
      km: 'ចំនួនប្រតិបត្តិការវិក្កយបត្រលក់ដែលបានចេញថ្ងៃនេះ',
      en: 'Total count of sales invoices processed today',
      zh: '今日处理的销售发票总数',
      th: 'จำนวนใบแจ้งหนี้การขายทั้งหมดที่ดำเนินการในวันนี้',
      vi: 'Tổng số hóa đơn bán hàng được xử lý hôm nay',
    },
    category: 'kpi',
    categoryLabel: {
      km: 'ពាណិជ្ជកម្ម & KPI',
      en: 'Commerce & KPI',
      zh: '商业与KPI',
      th: 'การค้า & KPI',
      vi: 'Thương mại & KPI',
    },
    icon: ShoppingCart,
    gradient: 'from-purple-500 to-violet-600',
    badgeColor: 'bg-purple-500/10 text-purple-600 dark:text-purple-400 border-purple-500/20',
    defaultSize: 'medium',
    defaultOrder: 2,
  },
  total_customers: {
    id: 'total_customers',
    name: {
      km: 'អតិថិជនសរុប (Total Customers)',
      en: 'Total Customers',
      zh: '客户总数',
      th: 'จำนวนลูกค้าทั้งหมด',
      vi: 'Tổng số khách hàng',
    },
    description: {
      km: 'ចំនួនអតិថិជនដែលបានចុះឈ្មោះ និងកំណើនអតិថិជន',
      en: 'Registered customer count and growth metrics',
      zh: '已注册客户数量及增长指标',
      th: 'จำนวนลูกค้าที่ลงทะเบียนและตัวเลขการเติบโต',
      vi: 'Số lượng khách hàng đã đăng ký và chỉ số phát triển',
    },
    category: 'kpi',
    categoryLabel: {
      km: 'ពាណិជ្ជកម្ម & KPI',
      en: 'Commerce & KPI',
      zh: '商业与KPI',
      th: 'การค้า & KPI',
      vi: 'Thương mại & KPI',
    },
    icon: Users,
    gradient: 'from-sky-500 to-cyan-600',
    badgeColor: 'bg-sky-500/10 text-sky-600 dark:text-sky-400 border-sky-500/20',
    defaultSize: 'medium',
    defaultOrder: 3,
  },
  total_products: {
    id: 'total_products',
    name: {
      km: 'ទំនិញសរុប (Total Products)',
      en: 'Total Products in Catalog',
      zh: '产品总数',
      th: 'จำนวนสินค้าทั้งหมด',
      vi: 'Tổng số sản phẩm',
    },
    description: {
      km: 'ចំនួនមុខទំនិញសរុបក្នុងកាតាឡុកប្រព័ន្ធ',
      en: 'Total number of catalog items in system database',
      zh: '系统数据库中的产品目录总数',
      th: 'จำนวนรายการสินค้าทั้งหมดในฐานข้อมูลระบบ',
      vi: 'Tổng số mặt hàng trong danh mục hệ thống',
    },
    category: 'inventory',
    categoryLabel: {
      km: 'ស្តុក & ទំនិញ',
      en: 'Inventory & Catalog',
      zh: '库存与目录',
      th: 'คลังสินค้า & รายการ',
      vi: 'Hàng tồn kho & Danh mục',
    },
    icon: Package,
    gradient: 'from-emerald-500 to-teal-600',
    badgeColor: 'bg-emerald-500/10 text-emerald-600 dark:text-emerald-400 border-emerald-500/20',
    defaultSize: 'medium',
    defaultOrder: 4,
  },
  sales_overview: {
    id: 'sales_overview',
    name: {
      km: 'ក្រាហ្វិកវិភាគការលក់',
      en: 'Sales Analytics Charts',
      zh: '销售分析图表',
      th: 'กราฟวิเคราะห์ยอดขาย',
      vi: 'Biểu đồ phân tích doanh số',
    },
    description: {
      km: 'ក្រាហ្វិកប្រៀបធៀបចំណូលប្រចាំសប្តាហ៍ ខែ និងប្រចាំឆ្នាំ',
      en: 'Weekly, monthly, and annual revenue analytics visual charts',
      zh: '周、月、年度收入分析可视化图表',
      th: 'กราฟแสดงการวิเคราะห์รายได้รายสัปดาห์ รายเดือน และรายปี',
      vi: 'Biểu đồ trực quan phân tích doanh thu hàng tuần, hàng tháng và hàng năm',
    },
    category: 'analytics',
    categoryLabel: {
      km: 'វិភាគ & ក្រាហ្វិក',
      en: 'Analytics & Visuals',
      zh: '分析与图表',
      th: 'วิเคราะห์ & กราฟ',
      vi: 'Phân tích & Biểu đồ',
    },
    icon: BarChart3,
    gradient: 'from-indigo-500 to-blue-600',
    badgeColor: 'bg-indigo-500/10 text-indigo-600 dark:text-indigo-400 border-indigo-500/20',
    defaultSize: 'large',
    defaultOrder: 5,
  },
  category_sales: {
    id: 'category_sales',
    name: {
      km: 'ការលក់តាមប្រភេទទំនិញ',
      en: 'Category Sales Breakdown',
      zh: '品类销售分布',
      th: 'สัดส่วนยอดขายตามหมวดหมู่',
      vi: 'Phân loại doanh số theo danh mục',
    },
    description: {
      km: 'ក្រាហ្វិកបង្ហាញភាគរយចំណូលតាមប្រភេទក្រុមទំនិញ',
      en: 'Breakdown pie/donut chart of revenue by product category',
      zh: '按产品类别划分的收入饼图/环形图',
      th: 'แผนภูมิวงกลมแสดงสัดส่วนรายได้ตามหมวดหมู่สินค้า',
      vi: 'Biểu đồ tròn phân tích doanh thu theo danh mục sản phẩm',
    },
    category: 'analytics',
    categoryLabel: {
      km: 'វិភាគ & ក្រាហ្វិក',
      en: 'Analytics & Visuals',
      zh: '分析与图表',
      th: 'วิเคราะห์ & กราฟ',
      vi: 'Phân tích & Biểu đồ',
    },
    icon: PieChart,
    gradient: 'from-fuchsia-500 to-pink-600',
    badgeColor: 'bg-fuchsia-500/10 text-fuchsia-600 dark:text-fuchsia-400 border-fuchsia-500/20',
    defaultSize: 'medium',
    defaultOrder: 6,
  },
  recent_orders: {
    id: 'recent_orders',
    name: {
      km: 'ការកុម្ម៉ង់ថ្មីៗ & ទំនិញលក់ដាច់',
      en: 'Recent Orders & Top Products',
      zh: '最新订单与热销商品',
      th: 'คำสั่งซื้อล่าสุด & สินค้าขายดี',
      vi: 'Đơn hàng mới & Sản phẩm bán chạy',
    },
    description: {
      km: 'បញ្ជីវិក្កយបត្រចុងក្រោយ ទំនិញលក់ដាច់បំផុត និងអតិថិជនថ្មីៗ',
      en: 'Live view of recent orders, top revenue products, and new customers',
      zh: '实时显示最新订单、高收入产品和新客户',
      th: 'มุมมองเรียลไทม์ของคำสั่งซื้อล่าสุด สินค้าทำรายได้สูงสุด และลูกค้าใหม่',
      vi: 'Xem thời gian thực đơn hàng gần đây, sản phẩm doanh thu cao và khách hàng mới',
    },
    category: 'kpi',
    categoryLabel: {
      km: 'ពាណិជ្ជកម្ម & KPI',
      en: 'Commerce & KPI',
      zh: '商业与KPI',
      th: 'การค้า & KPI',
      vi: 'Thương mại & KPI',
    },
    icon: ShoppingBag,
    gradient: 'from-blue-600 to-indigo-700',
    badgeColor: 'bg-blue-600/10 text-blue-700 dark:text-blue-300 border-blue-600/20',
    defaultSize: 'large',
    defaultOrder: 7,
  },
  low_stock: {
    id: 'low_stock',
    name: {
      km: 'ទំនិញជិតអស់ស្តុក & ឃ្លាំង',
      en: 'Low Stock & Warehouse Alerts',
      zh: '低库存与仓库警报',
      th: 'เตือนสินค้าใกล้หมด & คลังสินค้า',
      vi: 'Cảnh báo sắp hết hàng & Kho',
    },
    description: {
      km: 'បញ្ជីទំនិញដែលជិតអស់ពីស្តុក និងការបែងចែកស្តុកតាមឃ្លាំង',
      en: 'Critical inventory stock level warnings and warehouse breakdown',
      zh: '关键库存水平警告及各仓库库存明细',
      th: 'คำเตือนระดับสต็อกสินค้าที่วิกฤตและการแบ่งตามคลังสินค้า',
      vi: 'Cảnh báo mức tồn kho quan trọng và phân bổ theo kho hàng',
    },
    category: 'inventory',
    categoryLabel: {
      km: 'ស្តុក & ទំនិញ',
      en: 'Inventory & Catalog',
      zh: '库存与目录',
      th: 'คลังสินค้า & รายการ',
      vi: 'Hàng tồn kho & Danh mục',
    },
    icon: AlertTriangle,
    gradient: 'from-rose-500 to-amber-600',
    badgeColor: 'bg-rose-500/10 text-rose-600 dark:text-rose-400 border-rose-500/20',
    defaultSize: 'large',
    defaultOrder: 8,
  },
  financial_metrics: {
    id: 'financial_metrics',
    name: {
      km: 'ព័ត៌មានហិរញ្ញវត្ថុ & ចំណេញ',
      en: 'Financial Metrics & Margins',
      zh: '财务指标与利润率',
      th: 'ตัวเลขทางการเงิน & กำไร',
      vi: 'Chỉ số tài chính & Lợi nhuận',
    },
    description: {
      km: 'សូចនាករប្រាក់ចំណេញដុល ចំណេញសុទ្ធ និងចំណាយប្រតិបត្តិការ',
      en: 'Gross profit, net profit margins, and operating expense breakdown',
      zh: '毛利、净利润率及运营费用明细',
      th: 'กำไรขั้นต้น อัตรากำไรสุทธิ และรายละเอียดค่าใช้จ่ายในการดำเนินงาน',
      vi: 'Lợi nhuận gộp, tỷ số lợi nhuận ròng và chi phí vận hành',
    },
    category: 'finance',
    categoryLabel: {
      km: 'ហិរញ្ញវត្ថុ & គណនេយ្យ',
      en: 'Finance & Accounting',
      zh: '财务与会计',
      th: 'การเงิน & บัญชี',
      vi: 'Tài chính & Kế toán',
    },
    icon: DollarSign,
    gradient: 'from-emerald-600 to-teal-700',
    badgeColor: 'bg-emerald-600/10 text-emerald-700 dark:text-emerald-300 border-emerald-600/20',
    defaultSize: 'large',
    defaultOrder: 9,
  },
  campaigns_promotions: {
    id: 'campaigns_promotions',
    name: {
      km: 'យុទ្ធនាការ និងប័ណ្ណបញ្ចុះតម្លៃ',
      en: 'Active Campaigns & Coupons',
      zh: '营销活动与优惠券',
      th: 'แคมเปญ & คูปองส่วนลด',
      vi: 'Chiến dịch & Mã giảm giá',
    },
    description: {
      km: 'បញ្ជីយុទ្ធនាការទីផ្សារ ប័ណ្ណបញ្ចុះតម្លៃ និងកម្មវិធីណែនាំ',
      en: 'Active marketing campaigns, coupon usages, and affiliate referrals',
      zh: '活跃的营销活动、优惠券使用情况及推荐返利',
      th: 'แคมเปญการตลาดที่เปิดอยู่ การใช้คูปอง และการแนะนำเพื่อน',
      vi: 'Các chiến dịch tiếp thị đang hoạt động, mã giảm giá và giới thiệu',
    },
    category: 'analytics',
    categoryLabel: {
      km: 'វិភាគ & ក្រាហ្វិក',
      en: 'Analytics & Visuals',
      zh: '分析与图表',
      th: 'วิเคราะห์ & กราฟ',
      vi: 'Phân tích & Biểu đồ',
    },
    icon: Megaphone,
    gradient: 'from-purple-600 to-pink-600',
    badgeColor: 'bg-purple-500/10 text-purple-600 dark:text-purple-400 border-purple-500/20',
    defaultSize: 'large',
    defaultOrder: 10,
  },
  customer_insights: {
    id: 'customer_insights',
    name: {
      km: 'ការវិភាគអតិថិជន & ទីតាំង',
      en: 'Customer Insights & Locations',
      zh: '客户洞察与地区分布',
      th: 'ข้อมูลลูกค้า & พื้นที่หลัก',
      vi: 'Phân tích khách hàng & Khu vực',
    },
    description: {
      km: 'កំណើនអតិថិជន ប្រភេទអតិថិជន និងតំបន់អតិថិជនសកម្មបំផុត',
      en: 'Customer growth, retention rates, and top active locations',
      zh: '客户增长、留存率及主要活跃地区',
      th: 'การเติบโตของลูกค้า อัตราการซื้อซ้ำ และพื้นที่ที่มีลูกค้ามากที่สุด',
      vi: 'Tăng trưởng khách hàng, tỷ lệ giữ chân và các khu vực hoạt động hàng đầu',
    },
    category: 'analytics',
    categoryLabel: {
      km: 'វិភាគ & ក្រាហ្វិក',
      en: 'Analytics & Visuals',
      zh: '分析与图表',
      th: 'วิเคราะห์ & กราฟ',
      vi: 'Phân tích & Biểu đồ',
    },
    icon: Smile,
    gradient: 'from-sky-500 to-indigo-600',
    badgeColor: 'bg-sky-500/10 text-sky-600 dark:text-sky-400 border-sky-500/20',
    defaultSize: 'large',
    defaultOrder: 11,
  },
  web_conversion: {
    id: 'web_conversion',
    name: {
      km: 'វិភាគទស្សនកិច្ចវេបសាយ',
      en: 'Web Traffic & Conversion',
      zh: '网站流量与转化率',
      th: 'ทราฟฟิก & อัตราแปลงเว็บ',
      vi: 'Lưu lượng truy cập & Chuyển đổi Web',
    },
    description: {
      km: 'អត្រាបំប្លែងការទស្សនា បញ្ជីទំព័រមើលច្រើន និងឧបករណ៍ប្រើប្រាស់',
      en: 'Web conversion rates, top visited pages, and visitor device breakdown',
      zh: '网站转化率、热门访问页面及访客设备分布',
      th: 'อัตราการแปลงยอด การเยี่ยมชมหน้าเว็บยอดนิยม และอุปกรณ์ของผู้เข้าชม',
      vi: 'Tỷ lệ chuyển đổi trang web, các trang được xem nhiều nhất và thiết bị truy cập',
    },
    category: 'analytics',
    categoryLabel: {
      km: 'វិភាគ & ក្រាហ្វិក',
      en: 'Analytics & Visuals',
      zh: '分析与图表',
      th: 'วิเคราะห์ & กราฟ',
      vi: 'Phân tích & Biểu đồ',
    },
    icon: Globe2,
    gradient: 'from-blue-500 to-cyan-600',
    badgeColor: 'bg-blue-500/10 text-blue-600 dark:text-blue-400 border-blue-500/20',
    defaultSize: 'large',
    defaultOrder: 12,
  },
  mobile_app: {
    id: 'mobile_app',
    name: {
      km: 'កម្មវិធីទូរស័ព្ទ & អ្នកប្រើប្រាស់',
      en: 'Mobile App Analytics',
      zh: '移动应用分析',
      th: 'แอปมือถือ & ผู้ใช้งาน',
      vi: 'Ứng dụng di động & Người dùng',
    },
    description: {
      km: 'ចំនួនទាញយកកម្មវិធី អ្នកប្រើប្រាស់សកម្មប្រចាំថ្ងៃ និង Push Notifications',
      en: 'App downloads, daily active users (DAU), and push notification delivery',
      zh: '应用下载量、每日活跃用户(DAU)及推送通知发送',
      th: 'ยอดดาวน์โหลดแอป ผู้ใช้งานประจำวัน (DAU) และการส่งแจ้งเตือน',
      vi: 'Lượt tải ứng dụng, người dùng hàng ngày (DAU) và thông báo đẩy',
    },
    category: 'analytics',
    categoryLabel: {
      km: 'វិភាគ & ក្រាហ្វិក',
      en: 'Analytics & Visuals',
      zh: '分析与图表',
      th: 'วิเคราะห์ & กราฟ',
      vi: 'Phân tích & Biểu đồ',
    },
    icon: Smartphone,
    gradient: 'from-indigo-500 to-purple-600',
    badgeColor: 'bg-indigo-500/10 text-indigo-600 dark:text-indigo-400 border-indigo-500/20',
    defaultSize: 'large',
    defaultOrder: 13,
  },
  staff_performance: {
    id: 'staff_performance',
    name: {
      km: 'វត្តមានបុគ្គលិក & បើកប្រាក់បៀវត្សរ៍',
      en: 'Staff Attendance & Performance',
      zh: '员工考勤与绩效',
      th: 'การเข้างาน & ผลงานพนักงาน',
      vi: 'Chấm công & Hiệu suất nhân viên',
    },
    description: {
      km: 'អត្រាវត្តមានបុគ្គលិក បុគ្គលិកឆ្នើមលក់ដាច់បំផុត និងកញ្ចប់បៀវត្សរ៍',
      en: 'Staff attendance rate, top POS sales champions, and active department stats',
      zh: '员工出勤率、POS销售冠军及部门统计',
      th: 'อัตราการเข้างานพนักงาน พนักงานขายยอดเยี่ยม และสถิติแผนก',
      vi: 'Tỷ lệ chấm công nhân viên, nhân viên bán hàng xuất sắc và các bộ phận',
    },
    category: 'system',
    categoryLabel: {
      km: 'ប្រព័ន្ធ & ការជូនដំណឹង',
      en: 'System & Alerts',
      zh: '系统与警报',
      th: 'ระบบและการแจ้งเตือน',
      vi: 'Hệ thống & Cảnh báo',
    },
    icon: UserCheck,
    gradient: 'from-blue-600 to-teal-600',
    badgeColor: 'bg-blue-600/10 text-blue-600 dark:text-blue-400 border-blue-600/20',
    defaultSize: 'large',
    defaultOrder: 14,
  },
  system_health: {
    id: 'system_health',
    name: {
      km: 'ស្ថានភាពប្រព័ន្ធ & សុខភាព',
      en: 'System Health Diagnostics',
      zh: '系统健康诊断',
      th: 'สถานะและสุขภาพระบบ',
      vi: 'Chẩn đoán sức khỏe hệ thống',
    },
    description: {
      km: 'ត្រួតពិនិត្យល្បឿន Server, Database Connection, និងសេវាកម្ម',
      en: 'Server performance monitor, database status, and API health response times',
      zh: '服务器性能监控、数据库状态及API响应时间',
      th: 'ตรวจสอบประสิทธิภาพเซิร์ฟเวอร์ สถานะฐานข้อมูล และความเร็ว API',
      vi: 'Giám sát hiệu suất máy chủ, trạng thái cơ sở dữ liệu và thời gian phản hồi API',
    },
    category: 'system',
    categoryLabel: {
      km: 'ប្រព័ន្ធ & ការជូនដំណឹង',
      en: 'System & Alerts',
      zh: '系统与警报',
      th: 'ระบบและการแจ้งเตือน',
      vi: 'Hệ thống & Cảnh báo',
    },
    icon: Activity,
    gradient: 'from-teal-500 to-cyan-600',
    badgeColor: 'bg-teal-500/10 text-teal-600 dark:text-teal-400 border-teal-500/20',
    defaultSize: 'large',
    defaultOrder: 15,
  },
  quick_actions: {
    id: 'quick_actions',
    name: {
      km: 'សកម្មភាពរហ័ស',
      en: 'Quick Actions Bar',
      zh: '快捷操作栏',
      th: 'แถบดำเนินการด่วน',
      vi: 'Thao tác nhanh',
    },
    description: {
      km: 'ប៊ូតុងផ្លូវកាត់សម្រាប់បង្កើតការលក់ថ្មី បន្ថែមទំនិញ ឬមើលរបាយការណ៍',
      en: 'Shortcut launchpad to quickly initiate sales, add products, or check reports',
      zh: '快速发起销售、添加产品或查看报告的快捷面板',
      th: 'ปุ่มลัดสำหรับเริ่มการขาย เพิ่มสินค้า หรือดูรายงานได้อย่างรวดเร็ว',
      vi: 'Bảng lối tắt để khởi tạo bán hàng, thêm sản phẩm hoặc xem báo cáo nhanh chóng',
    },
    category: 'kpi',
    categoryLabel: {
      km: 'ពាណិជ្ជកម្ម & KPI',
      en: 'Commerce & KPI',
      zh: '商业与KPI',
      th: 'การค้า & KPI',
      vi: 'Thương mại & KPI',
    },
    icon: Zap,
    gradient: 'from-amber-500 to-yellow-600',
    badgeColor: 'bg-amber-500/10 text-amber-600 dark:text-amber-400 border-amber-500/20',
    defaultSize: 'medium',
    defaultOrder: 16,
  },
  recent_activities: {
    id: 'recent_activities',
    name: {
      km: 'កំណត់ហេតុសកម្មភាពថ្មីៗ',
      en: 'Recent Activity Timeline',
      zh: '最新活动日志',
      th: 'ประวัติกิจกรรมล่าสุด',
      vi: 'Nhật ký hoạt động gần đây',
    },
    description: {
      km: 'បន្ទាត់ពេលវេលានៃសកម្មភាពអ្នកប្រើប្រាស់ និងប្រតិបត្តិការចុងក្រោយ',
      en: 'Chronological timeline of real-time user updates and audit logs',
      zh: '按时间顺序排列的实时用户更新和审计日志',
      th: 'ลำดับเวลาของกิจกรรมผู้ใช้และบันทึกการตรวจสอบแบบเรียลไทม์',
      vi: 'Nhật ký thời gian thực về hoạt động người dùng và kiểm toán',
    },
    category: 'system',
    categoryLabel: {
      km: 'ប្រព័ន្ធ & ការជូនដំណឹង',
      en: 'System & Alerts',
      zh: '系统与警报',
      th: 'ระบบและการแจ้งเตือน',
      vi: 'Hệ thống & Cảnh báo',
    },
    icon: Clock,
    gradient: 'from-slate-600 to-slate-800',
    badgeColor: 'bg-slate-500/10 text-slate-600 dark:text-slate-400 border-slate-500/20',
    defaultSize: 'medium',
    defaultOrder: 17,
  },
}

export const DEFAULT_WIDGETS_LIST = Object.values(DASHBOARD_WIDGET_REGISTRY).map((w) => ({
  id: w.id,
  visible: true,
  size: w.defaultSize,
  order: w.defaultOrder,
}))

export const PRESET_LAYOUTS = [
  {
    id: 'default',
    name: {
      km: 'ទម្រង់ដើមប្រព័ន្ធ',
      en: 'Standard Default',
      zh: '标准默认',
      th: 'ค่าเริ่มต้นมาตรฐาน',
      vi: 'Mặc định chuẩn',
    },
    desc: {
      km: 'បង្ហាញ widgets ទាំងអស់តាមលំដាប់លំដោយស្តង់ដារ',
      en: 'Shows all widgets in balanced standard order',
      zh: '按标准平衡顺序显示所有组件',
      th: 'แสดงส่วนประกอบทั้งหมดในลำดับมาตรฐาน',
      vi: 'Hiển thị tất cả các tiện ích theo thứ tự chuẩn',
    },
  },
  {
    id: 'sales_focus',
    name: {
      km: 'ផ្តោតលើការលក់ & KPI',
      en: 'Sales & KPI Focus',
      zh: '侧重销售与KPI',
      th: 'เน้นการขาย & KPI',
      vi: 'Tập trung Doanh số & KPI',
    },
    desc: {
      km: 'បង្ហាញតែ widgets ការលក់ ចំណូល វិក្កយបត្រ និងក្រាហ្វិកវិភាគ',
      en: 'Prioritizes sales metrics, orders, revenue charts, and top items',
      zh: '优先显示销售指标、订单、收入图表及热门商品',
      th: 'ให้ความสำคัญกับยอดขาย คำสั่งซื้อ กราฟรายได้ และสินค้าขายดี',
      vi: 'Ưu tiên chỉ số doanh số, đơn hàng, biểu đồ doanh thu và mặt hàng nổi bật',
    },
  },
  {
    id: 'inventory_focus',
    name: {
      km: 'ផ្តោតលើស្តុក & ឃ្លាំង',
      en: 'Inventory Focus',
      zh: '侧重库存与仓库',
      th: 'เน้นคลังสินค้า',
      vi: 'Tập trung Hàng tồn kho',
    },
    desc: {
      km: 'បង្ហាញ widgets ទំនិញ ស្តុកជិតអស់ ឃ្លាំង និងដំណឹងអាជីវកម្ម',
      en: 'Prioritizes product catalog, low stock alerts, and warehouse analytics',
      zh: '优先显示产品目录、低库存警报及仓库分析',
      th: 'เน้นรายการสินค้า เตือนสต็อกต่ำ และการวิเคราะห์คลังสินค้า',
      vi: 'Ưu tiên danh mục sản phẩm, cảnh báo kho thấp và phân tích kho',
    },
  },
  {
    id: 'compact',
    name: {
      km: 'ទម្រង់បង្រួមតូច',
      en: 'Compact Minimal',
      zh: '精简紧凑模式',
      th: 'โหมดกะทัดรัด',
      vi: 'Giao diện thu nhỏ',
    },
    desc: {
      km: 'លាក់ widgets មិនចាំបាច់ ដើម្បីមើលតែ metrics សំខាន់ៗបំផុត',
      en: 'Hides low priority widgets for a clutter-free executive view',
      zh: '隐藏次要组件，提供清晰的高管视图',
      th: 'ซ่อนส่วนประกอบที่ไม่จำเป็นเพื่อมุมมองที่สะอาดตา',
      vi: 'Ẩn các tiện ích phụ để có góc nhìn tổng quan gọn gàng',
    },
  },
]

export function getWidgetLocalizedString(
  strObj: MultiLangString | undefined,
  lang: string
): string {
  if (!strObj) return ''
  const validLang = (['km', 'en', 'zh', 'th', 'vi'].includes(lang) ? lang : 'km') as SupportedLang
  return strObj[validLang] || strObj.km || strObj.en || ''
}
